post_creator_task:
  description: >
    Generate a {platform} post using the provided content on the given topic: '{topic}' 
    and add the image url list {images} in the post. Ensure the post is optimized for 
    engagement, includes appropriate hashtags and image url list 'images'.
  expected_output: >
    A complete, ready-to-publish {platform} post formatted with line breaks, hashtags, 
    and image url list.
  agent: post_creator_agent